#! /usr/bin/env python

# (c) 2007 The Board of Trustees of the University of Illinois.

import sys

def checkout_dataset():
  import os
  if not os.path.exists("datasets"):
    import urllib
    print "Datasets are being downloaded and installed. It will take a few minutes."
    url = "https://bitbucket.org/hwuligans/public/downloads/datasets.tar.bz2"
    datafile = "datasets.tar.bz2"
    urllib.urlretrieve (url, datafile)

    import os
    import tarfile
    import zipfile
    def extract_file(path, to_directory='.'):
      if path.endswith('.zip'):
        opener, mode = zipfile.ZipFile, 'r'
      elif path.endswith('.tar.gz') or path.endswith('.tgz'):
        opener, mode = tarfile.open, 'r:gz'
      elif path.endswith('.tar.bz2') or path.endswith('.tbz'):
        opener, mode = tarfile.open, 'r:bz2'
      else: 
        raise ValueError, "Could not extract `%s` as no appropriate extractor is found" % path
      
      cwd = os.getcwd()
      os.chdir(to_directory)
      
      try:
        file = opener(path, mode)
        try: file.extractall()
        finally: file.close()
      finally:
        os.chdir(cwd)

    extract_file(datafile)
    print "Done. You may delete %s." % datafile

try:
  checkout_dataset()
  import driver
except ImportError:
  sys.stderr.write("Cannot run driver.  Are you running it from the parboil root directory?")
  sys.exit(-1)

sys.exit(driver.run())

